[package]
name = "gst-inspect-rs"
license = "LGPL-2.1-only"
license-file = "COPYING"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
